INFO:django.utils.autoreload:/Users/Tatsuki/projects/django/book_shop_api/members/views.py changed, reloading.
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:post前
INFO:root:post後
INFO:root:is_valid
ERROR:django.request:Internal Server Error: /member_api/create
Traceback (most recent call last):
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/renderers.py", line 103, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type property is not JSON serializable
INFO:django.utils.autoreload:/Users/Tatsuki/projects/django/book_shop_api/members/views.py changed, reloading.
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:post前
INFO:root:post後
INFO:root:is_valid
ERROR:django.request:Internal Server Error: /member_api/create
Traceback (most recent call last):
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Tatsuki/projects/django/book_shop_api/members/views.py", line 20, in post
    return Response(serializer.data)
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/Users/Tatsuki/anaconda3/envs/book_shop_api/lib/python3.7/site-packages/rest_framework/serializers.py", line 256, in data
    raise AssertionError(msg)
AssertionError: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
INFO:django.utils.autoreload:/Users/Tatsuki/projects/django/book_shop_api/members/views.py changed, reloading.
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:post前
INFO:django.utils.autoreload:/Users/Tatsuki/projects/django/book_shop_api/members/views.py changed, reloading.
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:post前
INFO:root:post後
INFO:django.utils.autoreload:/Users/Tatsuki/projects/django/book_shop_api/members/serializers.py changed, reloading.
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:post前
INFO:root:post後
INFO:django.utils.autoreload:/Users/Tatsuki/projects/django/book_shop_api/members/serializers.py changed, reloading.
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:post前
INFO:root:post前
